{
  "bugzilla": {
    "description": "kernel: phonet/pep: refuse to enable an unbound pipe",
    "id": "2267939",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2267939"
  },
  "csaw": false,
  "cvss3": {
    "cvss3_base_score": "5.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "cwe": "CWE-20",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\nphonet/pep: refuse to enable an unbound pipe\nThis ioctl() implicitly assumed that the socket was already bound to\na valid local socket name, i.e. Phonet object. If the socket was not\nbound, two separate problems would occur:\n1) We'd send an pipe enablement request with an invalid source object.\n2) Later socket calls could BUG on the socket unexpectedly being\nconnected yet not bound to a valid object."
  ],
  "name": "CVE-2021-47086",
  "package_state": [
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:6",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "product_name": "Red Hat Enterprise Linux 6"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:7",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "product_name": "Red Hat Enterprise Linux 7"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:7",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "product_name": "Red Hat Enterprise Linux 7"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:8",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "product_name": "Red Hat Enterprise Linux 8"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:8",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "product_name": "Red Hat Enterprise Linux 8"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:9",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "product_name": "Red Hat Enterprise Linux 9"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:9",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "product_name": "Red Hat Enterprise Linux 9"
    }
  ],
  "public_date": "2024-03-04T00:00:00Z",
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2021-47086\nhttps://nvd.nist.gov/vuln/detail/CVE-2021-47086\nhttps://lore.kernel.org/linux-cve-announce/2024030455-CVE-2021-47086-cdaa@gregkh/T"
  ],
  "threat_severity": "Moderate",
  "upstream_fix": "kernel 4.4.297, kernel 4.9.295, kernel 4.14.260, kernel 4.19.223, kernel 5.4.169, kernel 5.10.89, kernel 5.15.12, kernel 5.16"
}